fix pre-commit script

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -1,17 +1,23 @@
 #!/bin/sh
 
-echo "Running black."
-git ls-files | grep "\.py$" |  xargs black
+# Run black
+a=$((git ls-files | grep "\.py$" |  xargs black) 2>&1 | grep "formatted")
+git ls-files | grep "\.py$" |  xargs black 2>/dev/null
 
 if [ $? -ne 0 ]; then
- echo "Black should pass before commit."
- exit 1
+  echo "\033[0;31mBlack failed. Commit aborted.\033[0m"
+  exit 1
+fi
+if [ -n "$a" ]
+then
+  echo "\033[0;31mBlack changed files. Commit aborted.\033[0m"
+  exit 1
 fi
 
-echo "Adding license header."
+# Add licenses
 ./.github/scripts/prepend_license.sh
 
 if [ $? -ne 0 ]; then
- echo "Could not add license header."
- exit 1
+  echo "\033[0;31mNew licenses added. Commit aborted.\033[0m"
+  exit 1
 fi
